services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx:alpine
    volumes:
      - ./server1:/usr/share/nginx/html

  web2:
    image: nginx:alpine
    volumes:
      - ./server2:/usr/share/nginx/html

  web3:
    image: nginx:alpine
    volumes:
      - ./server3:/usr/share/nginx/html