# Configuração de mTLS no Istio em modo PERMISSIVE
# Neste modo, o Istio aceita tráfego criptografado (mTLS) e também tráfego em texto puro.
# Útil para migrações graduais sem quebrar comunicações de pods sem sidecar.

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default              # Nome da configuração (padrão, aplicada em todo o mesh)
  namespace: istio-system    # Namespace do Istio (aplica globalmente no mesh)
spec:
  mtls:
    mode: PERMISSIVE          # Modo permissivo: aceita mTLS e também plain-text
