services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: apache-server
    ports:
      - "8080:80"
    volumes:
      - ./apache/html:/usr/local/apache2/htdocs:ro
      - ./apache/logs:/usr/local/apache2/logs
    restart: unless-stopped

  nginx-web:
    image: nginx:1.25.3-alpine
    container_name: meu-nginx-hands-on
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./html1:/usr/share/nginx/html1:ro
      - ./html2:/usr/share/nginx/html2:ro
    restart: unless-stopped
