services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - labnet

  api:
    build: ./api
    expose:
      - "5000"
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
